site_name: Docs
theme:
  name: material
  logo: assets/logo_white.svg
  favicon: images/favicon.ico
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - toc.integrate
    - navigation.sections
    - navigation.expand
    - navigation.top
extra_css:
  - stylesheets/extra.css
extra:
  homepage: https://dstack.ai
  generator: false
nav:
  - Quickstart: index.md
  - Tutorials:
    - Training GPT-2: tutorials.md