site_name: dstack.ai
#repo_url: https://github.com/dstackai/dstackai.github.io
#edit_uri: edit/main/docs/
theme:
  name: material
  logo: assets/dstack_notext.png
  favicon: images/dstack_fav_32.ico
  icon:
    repo: fontawesome/brands/github
  font: false
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    #    - toc.integrate
    - navigation.sections
    - navigation.expand
    - navigation.top
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      toc_depth: 4
extra_css:
  - stylesheets/extra.css
extra:
  homepage: https://dstack.ai
  generator: false
  analytics:
    provider: google
    property: UA-4493451-5
nav:
  - Get started:
      - How it works: index.md
      - Installation: installation.md
      - Self-hosted runners: self-hosted-runners.md
      - Spot instances: spot-instances.md
      - Define workflows: define-wokflows.md
      - Run workflows: run-workflows.md
  - Examples:
      - GPT-2: gpt-2.md