site_name: dstack.ai
#repo_url: https://github.com/dstackai/dstackai.github.io
#edit_uri: edit/main/docs/
theme:
  name: material
  logo: assets/dstack_notext.png
  favicon: images/dstack_fav_32.ico
  icon:
    repo: fontawesome/brands/github
  font:
    text: Source Sans Pro
    code: IBM Plex Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: lilac
#      toggle:
#        icon: material/weather-night
#        name: Switch to dark mode
#    - media: "(prefers-color-scheme: dark)"
#      scheme: slate
#      primary: black
#      accent: light blue
#      toggle:
#        icon: material/weather-sunny
#        name: Switch to light mode
  features:
    - toc.integrate
    - navigation.sections
#    - navigation.expand
    - navigation.top
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - def_list
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      toc_depth: 2
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
extra:
  homepage: https://dstack.ai
  generator: false
  analytics:
    provider: google
    property: UA-4493451-5
nav:
  - Get started:
      - Overview: index.md
      - Installation: installation.md
      - Workflows: workflows.md
      - Runners:
        - On-demand runners: on-demand-runners.md
        - Self-hosted runners: self-hosted-runners.md
  - Examples:
      - GPT-2: gpt-2.md
  - Help:
    - Community: https://join.slack.com/t/dstackai/shared_invite/zt-xdnsytie-D4qU9BvJP8vkbkHXdi6clQ
    - Open a chat 💬: "javascript:$crisp.push(['do', 'chat:show']);$crisp.push(['do', 'chat:open']);"