site_name: dstack.ai
#repo_url: https://github.com/dstackai/dstackai.github.io
#edit_uri: edit/main/docs/
theme:
  name: material
  logo: assets/logo_dark.svg
  favicon: images/favicon.ico
  icon:
    repo: fontawesome/brands/github
  font: false
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
#    - toc.integrate
#    - navigation.sections
    - navigation.expand
    - navigation.top
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      toc_depth: 4
extra_css:
  - stylesheets/extra.css
extra:
  homepage: https://dstack.ai
  generator: false
  analytics:
    provider: google
    property: UA-4493451-5
nav:
  - Getting started:
    - Overview: index.md
    - Installation: install-cli.md
    - Runners:
      - Own servers: set-up-own-runners.md
    - Workflows: define-wokflows.md
    - CLI commands: run-workflows.md
  - Tutorials:
      - GPT-2: gpt-2.md
  - Limitations: limitations.md